drop table if exists member CASCADE;
create table member
(
	id bigint generated by default as identity,     -- bigint: java의 long / generated by ... : DB가 자동으로 값을 채워줌
	name varchar(255),
	primary key (id)
);